<#
.SYNOPSIS
  Fan the shared global prompt out to every AI CLI's global instruction location.

.DESCRIPTION
  Three files are synced:

    global-prompt.md   — public, vendor- and machine-neutral. Lives in this repo.
    global-machine.md  — host names, LAN IPs, account and project ids. Lives ONLY
                         in ~/.claude (this repo is public), and is the source of
                         truth for its copies.
    gsd-settings.md    — canonical GSD config, branching, worktree HEAD fix, and
                         the milestone close ritual. Lives in this repo. NOT
                         imported by any instruction file — it is read on demand,
                         so it costs no context until an agent needs it.

  Windows without Developer Mode refuses non-admin symlinks, so all are copied
  rather than linked. Re-run this after editing any of them.

  Claude and Gemini support @-imports, so they get side-car files and import
  them. Codex has no import mechanism, so its AGENTS.md carries the prompt and
  the machine file inline behind a generated-file header. Anything above that
  header is Codex-specific and is PRESERVED across runs.
#>
[CmdletBinding()]
param(
    [string]$Source = (Join-Path $PSScriptRoot 'global-prompt.md')
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path $Source)) { throw "Source not found: $Source" }
$body = Get-Content $Source -Raw
$home_ = $env:USERPROFILE

# global-machine.md is machine-local and never lives in this repo.
$machineSource = "$home_\.claude\global-machine.md"
$machineBody = if (Test-Path $machineSource) { Get-Content $machineSource -Raw } else {
    Write-Warning "No global-machine.md in ~/.claude — syncing the neutral prompt only."
    $null
}

# gsd-settings.md rides along so `global-prompt.md`'s pointer to it resolves from
# every CLI's config directory.
$gsdSource = Join-Path $PSScriptRoot 'gsd-settings.md'
$gsdBody = if (Test-Path $gsdSource) { Get-Content $gsdSource -Raw } else {
    Write-Warning "No gsd-settings.md beside the script — the milestone-ritual pointer will dangle."
    $null
}

$targets = @("$home_\.claude", "$home_\.gemini", "$home_\.codex")

# --- gsd-settings.md: plain copy everywhere, read on demand, imported nowhere ---
foreach ($dir in $targets) {
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir | Out-Null }
    if ($gsdBody) {
        Set-Content -Path (Join-Path $dir 'gsd-settings.md') -Value $gsdBody -NoNewline
        Write-Host "synced -> $dir\gsd-settings.md"
    }
}

# --- Claude + Gemini: side-car files, imported by the instruction file ---
foreach ($dir in @("$home_\.claude", "$home_\.gemini")) {
    Set-Content -Path (Join-Path $dir 'global-prompt.md') -Value $body -NoNewline
    Write-Host "synced -> $dir\global-prompt.md"
    if ($machineBody -and $dir -ne "$home_\.claude") {
        Set-Content -Path (Join-Path $dir 'global-machine.md') -Value $machineBody -NoNewline
        Write-Host "synced -> $dir\global-machine.md"
    }
}

# --- Codex: no imports, inline both, keep any Codex-specific preamble ---
$codexPath = "$home_\.codex\AGENTS.md"
$marker = '<!-- GENERATED by sync-global-prompt.ps1'

# Everything above the marker is hand-written Codex-only guidance. Carry it over.
# A file with no marker was not written by this script, so treat ALL of it as
# hand-written rather than destroying it.
$preamble = ''
if (Test-Path $codexPath) {
    $existing = Get-Content $codexPath -Raw
    $idx = $existing.IndexOf($marker)
    if ($idx -ge 0) {
        $preamble = $existing.Substring(0, $idx)
    } elseif ($existing.Trim()) {
        Write-Warning "AGENTS.md has no generated marker — preserving the whole file as a preamble. Trim it by hand if it duplicates the global prompt."
        $preamble = $existing.TrimEnd() + "`n`n"
    }
}
if ($preamble.Trim()) {
    Write-Host ("preserved  <- {0} lines of Codex-specific preamble" -f ($preamble.TrimEnd() -split "`n").Count)
}

$header = @"
<!-- GENERATED by sync-global-prompt.ps1 from jonvickers/templates/global-prompt.md
     plus the machine-local global-machine.md. Codex has no @-import mechanism, so
     both are inlined here. Edit the sources, not this file, then re-run the
     script. Codex-specific instructions go ABOVE this marker; the script keeps
     them. -->

"@
$codexBody = if ($machineBody) { $preamble + $header + $body + "`n---`n`n" + $machineBody } else { $preamble + $header + $body }
Set-Content -Path $codexPath -Value $codexBody -NoNewline
Write-Host "synced -> $codexPath (inlined)"
