<#
.SYNOPSIS
  Fan the shared global prompt out to every AI CLI's global instruction location.

.DESCRIPTION
  Three files are synced:

    global-prompt.md   — public, vendor- and machine-neutral. Lives in this repo.
    global-machine.md  — host names, LAN IPs, account and project ids. Lives ONLY
                         in ~/.claude (this repo is public), and is the source of
                         truth for its copies.
    gsd-settings.md    — canonical GSD config, branching, worktree HEAD fix,
                         review lanes, and the milestone close ritual. Lives in
                         this repo.
    ai-setup-audit.md  — the machine-level AI/agent health work order. Lives in
                         this repo.

  The last two are NOT imported by any instruction file — they are read on
  demand, so they cost no context until an agent needs them.

  Windows without Developer Mode refuses non-admin symlinks, so all are copied
  rather than linked. Re-run this after editing any of them.

  Claude and Gemini support @-imports, so they get side-car files and import
  them. Codex has no import mechanism, so its AGENTS.md carries the prompt and
  the machine file inline behind a generated-file header. Anything above that
  header is Codex-specific and is PRESERVED across runs.
#>
[CmdletBinding()]
param(
    [string]$Source = (Join-Path $PSScriptRoot 'global-prompt.md')
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path $Source)) { throw "Source not found: $Source" }
$body = Get-Content $Source -Raw

# Cross-platform home. $env:USERPROFILE is Windows-only — on macOS/Linux pwsh it
# is empty, which silently turned every target into a filesystem-root path.
$home_ = if ($env:USERPROFILE) { $env:USERPROFILE } elseif ($env:HOME) { $env:HOME } else { $HOME }
if (-not $home_) { throw "Could not resolve a home directory (USERPROFILE, HOME and `$HOME are all empty)." }

# global-machine.md is machine-local and never lives in this repo.
$machineSource = Join-Path $home_ '.claude/global-machine.md'
$machineBody = if (Test-Path $machineSource) { Get-Content $machineSource -Raw } else {
    Write-Warning "No global-machine.md in ~/.claude — syncing the neutral prompt only."
    $null
}

# These ride along so `global-prompt.md`'s pointers to them resolve from every
# CLI's config directory. Read on demand, imported nowhere — zero context cost.
$onDemand = @('gsd-settings.md', 'ai-setup-audit.md')
$onDemandBodies = @{}
foreach ($name in $onDemand) {
    $path = Join-Path $PSScriptRoot $name
    if (Test-Path $path) {
        $onDemandBodies[$name] = Get-Content $path -Raw
    } else {
        Write-Warning "No $name beside the script — the pointer to it will dangle."
    }
}

$targets = @((Join-Path $home_ ".claude"), (Join-Path $home_ ".gemini"), (Join-Path $home_ ".codex"))

# --- read-on-demand files: plain copy everywhere, imported nowhere ---
foreach ($dir in $targets) {
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir | Out-Null }
    foreach ($name in $onDemand) {
        if ($onDemandBodies.ContainsKey($name)) {
            Set-Content -Path (Join-Path $dir $name) -Value $onDemandBodies[$name] -NoNewline
            Write-Host "synced -> $dir\$name"
        }
    }
}

# --- Claude + Gemini: side-car files, imported by the instruction file ---
foreach ($dir in @((Join-Path $home_ ".claude"), (Join-Path $home_ ".gemini"))) {
    Set-Content -Path (Join-Path $dir 'global-prompt.md') -Value $body -NoNewline
    Write-Host "synced -> $dir\global-prompt.md"
    if ($machineBody -and $dir -ne (Join-Path $home_ ".claude")) {
        Set-Content -Path (Join-Path $dir 'global-machine.md') -Value $machineBody -NoNewline
        Write-Host "synced -> $dir\global-machine.md"
    }
}

# --- Codex: no imports, inline both, keep any Codex-specific preamble ---
$codexPath = Join-Path $home_ '.codex/AGENTS.md'
$marker = '<!-- GENERATED by sync-global-prompt.ps1'

# Everything above the marker is hand-written Codex-only guidance. Carry it over.
# A file with no marker was not written by this script, so treat ALL of it as
# hand-written rather than destroying it.
$preamble = ''
if (Test-Path $codexPath) {
    $existing = Get-Content $codexPath -Raw
    $idx = $existing.IndexOf($marker)
    if ($idx -ge 0) {
        $preamble = $existing.Substring(0, $idx)
    } elseif ($existing.Trim()) {
        Write-Warning "AGENTS.md has no generated marker — preserving the whole file as a preamble. Trim it by hand if it duplicates the global prompt."
        $preamble = $existing.TrimEnd() + "`n`n"
    }
}
if ($preamble.Trim()) {
    Write-Host ("preserved  <- {0} lines of Codex-specific preamble" -f ($preamble.TrimEnd() -split "`n").Count)
}

$header = @"
<!-- GENERATED by sync-global-prompt.ps1 — inlines templates/global-prompt.md and
     the machine-local global-machine.md (Codex has no @-import). Edit the
     sources and re-run; Codex-specific text above this marker is preserved. -->

"@
$codexBody = if ($machineBody) { $preamble + $header + $body + "`n---`n`n" + $machineBody } else { $preamble + $header + $body }
Set-Content -Path $codexPath -Value $codexBody -NoNewline
Write-Host "synced -> $codexPath (inlined)"
