<#
.SYNOPSIS
  Fan the shared global prompt out to every AI CLI's global instruction location.

.DESCRIPTION
  Two files are synced:

    global-prompt.md   — public, vendor- and machine-neutral. Lives in this repo.
    global-machine.md  — host names, LAN IPs, account and project ids. Lives ONLY
                         in ~/.claude (this repo is public), and is the source of
                         truth for its copies.

  Windows without Developer Mode refuses non-admin symlinks, so both are copied
  rather than linked. Re-run this after editing either one.

  Claude and Gemini support @-imports, so they get side-car files and import
  them. Codex has no import mechanism, so its AGENTS.md carries both inline
  behind a generated-file header.
#>
[CmdletBinding()]
param(
    [string]$Source = (Join-Path $PSScriptRoot 'global-prompt.md')
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path $Source)) { throw "Source not found: $Source" }
$body = Get-Content $Source -Raw
$home_ = $env:USERPROFILE

# global-machine.md is machine-local and never lives in this repo.
$machineSource = "$home_\.claude\global-machine.md"
$machineBody = if (Test-Path $machineSource) { Get-Content $machineSource -Raw } else {
    Write-Warning "No global-machine.md in ~/.claude — syncing the neutral prompt only."
    $null
}

# --- Claude + Gemini: side-car files, imported by the instruction file ---
foreach ($dir in @("$home_\.claude", "$home_\.gemini")) {
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir | Out-Null }
    Set-Content -Path (Join-Path $dir 'global-prompt.md') -Value $body -NoNewline
    Write-Host "synced -> $dir\global-prompt.md"
    if ($machineBody -and $dir -ne "$home_\.claude") {
        Set-Content -Path (Join-Path $dir 'global-machine.md') -Value $machineBody -NoNewline
        Write-Host "synced -> $dir\global-machine.md"
    }
}

# --- Codex: no imports, inline both ---
$codexDir = "$home_\.codex"
if (-not (Test-Path $codexDir)) { New-Item -ItemType Directory -Path $codexDir | Out-Null }
$header = @"
<!-- GENERATED by sync-global-prompt.ps1 from jonvickers/templates/global-prompt.md
     plus the machine-local global-machine.md. Codex has no @-import mechanism, so
     both are inlined here. Edit the sources, not this file, then re-run the
     script. Codex-specific instructions go ABOVE this marker. -->

"@
$codexBody = if ($machineBody) { $header + $body + "`n---`n`n" + $machineBody } else { $header + $body }
Set-Content -Path (Join-Path $codexDir 'AGENTS.md') -Value $codexBody -NoNewline
Write-Host "synced -> $codexDir\AGENTS.md (inlined)"
